name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        # Decrypt and copy sings file
      - name: Decrypt sings file
        run: ./decryptors/decrypt_sings_file.sh
        env:
          FAMOUS_QUOTES_KEY: ${{ secrets.FAMOUS_QUOTES_KEY }}
      - name: Copy signs file
        run: cp $HOME/secrets/famousQuotes.jks /home/runner/work/FamousQuotes/FamousQuotes/signing/


        # Decrypt and copy signing.properties file
      - name: Decrypt signing.properties
        run: ./decryptors/decrypt_signing_properties.sh
        env:
          FAMOUS_QUOTES_KEY: ${{ secrets.FAMOUS_QUOTES_KEY }}
      - name: Copy signing.properties
        run: cp $HOME/secrets/signing.properties /home/runner/work/FamousQuotes/FamousQuotes/signing/


        # Decrypt and copy admob.properties file
      - name: Decrypt admob.properties
        run: ./decryptors/decrypt_admob_properties.sh
        env:
          FAMOUS_QUOTES_KEY: ${{ secrets.FAMOUS_QUOTES_KEY }}
      - name: Copy admob.properties
        run: cp $HOME/secrets/admob.properties /home/runner/work/FamousQuotes/FamousQuotes/admob/


        # Decrypt and copy google.service.json
      - name: Decrypt google.service.json
        run: ./decryptors/decrypt_google_service.sh
        env:
          FAMOUS_QUOTES_KEY: ${{ secrets.FAMOUS_QUOTES_KEY }}
      - name: Copy google.service.json
        run: cp $HOME/secrets/google-services.json /home/runner/work/FamousQuotes/FamousQuotes/app/


        # Setup JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle


        # Increase memory
      - name: Increase memory for Gradle
        run: ./gradlew assemble -Dorg.gradle.jvmargs="-Xmx4g"


        # Setup gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      # Clean Gradle before start
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches/

      # Start Gradle's tasks
      - name: Run clean
        run: ./gradlew clean -Dorg.gradle.jvmargs="-Xmx4g" --warn --stacktrace
      - name: Compile debug sources
        run: ./gradlew compileDebugSources -Dorg.gradle.jvmargs="-Xmx4g" --warn --stacktrace
      - name: Package debug
        run: ./gradlew packageDebug -Dorg.gradle.jvmargs="-Xmx4g" --warn --stacktrace
